AWSTemplateFormatVersion: "2010-09-09"

Description: >
  AWS Batch Cloudformation Template Example

  Builds a Small VPC with a small public Subnet.

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock:  10.0.0.0/24  # 10.0.0.0 - 10.0.0.255

  PublicSubnetInternetGateway:
    Type: AWS::EC2::InternetGateway

  VpcGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref PublicSubnetInternetGateway
      VpcId: !Ref VPC
    DependsOn:
      - VPC
      - PublicSubnetInternetGateway

  PublicSubnetRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
    DependsOn: VPC

  PublicSubnetRoute:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0  # Route all traffic freely
      GatewayId: !Ref PublicSubnetInternetGateway
      RouteTableId: !Ref PublicSubnetRouteTable
    DependsOn: 
      - PublicSubnetRouteTable
      - VpcGatewayAttachment

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.0.0/26  # 10.0.0.0 - 10.0.0.63
      MapPublicIpOnLaunch: true
      VpcId: !Ref VPC
      AvailabilityZone: !Select [0, !GetAZs ""]
    DependsOn: VPC

  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicSubnetRouteTable
      SubnetId: !Ref PublicSubnet
    DependsOn:
      - PublicSubnetRouteTable
      - PublicSubnet

  # PublicSubnetFailover:
  #   Type: AWS::EC2::Subnet
  #   Properties:
  #     CidrBlock: 10.0.0.64/26  # 10.0.0.64 - 10.0.0.127
  #     MapPublicIpOnLaunch: true
  #     VpcId: !Ref VPC
  #     AvailabilityZone: !Select [1, !GetAZs ""]

Outputs:
  VPC:
    Description: ID of created VPC
    Value: !Ref VPC
    Export:
      Name: !Sub "${AWS::StackName}-vpc"

  Subnets:
    Description: List of created Subnet IDs
    Value: !Join [",", [!Ref PublicSubnet] ]
    Export:
      Name: !Sub "${AWS::StackName}-subnets"
